## CI config and data
variables:
  IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  IMAGE_BRANCH_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_RELEASE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

stages:
  - test
  - docker
  - docker-push

# Node specific definition for test
.node_scripts_test: &shared_node_scripts_test
  image: node:10-alpine
  tags:
    - cli
  before_script:
    - node -v
    - npm --version
    - yarn --version
    - yarn
  coverage: '/^Statements\s*:\s*([^%]+)/'
  cache:
    key: "cli-$CI_COMMIT_REF_SLUG"
    untracked: true
    paths:
      - node_modules/
  only:
    - merge_requests
    - master
    - tags

# Docker scripts and config
.docker_config: &shared_docker_config
  tags:
    - cli
  variables:
    DOCKER_DRIVER: overlay2
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

# Tag matchers

.release_tag_selector: &release_tag_selector
  only:
    - /^(v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?)|(([a-zA-Z][0-9]-){2}[a-zA-Z][0-9])$/
    - tags
  except:
    - branches

########################################

## Steps

#
##  Test
#

test:
  stage: test
  <<: *shared_node_scripts_test
  script:
    - npm run test

#
##  Docker
#

docker:latest:
  stage: docker
  <<: *shared_docker_config
  script:
    - docker pull $IMAGE_LATEST_TAG
    - docker build --cache-from $IMAGE_LATEST_TAG -t $IMAGE_LATEST_TAG .
    - docker push $IMAGE_LATEST_TAG
    - docker rmi $IMAGE_LATEST_TAG
  only:
    - master

docker:release:
  stage: docker
  <<: *shared_docker_config
  script:
    - docker pull $IMAGE_LATEST_TAG
    - docker build --cache-from $IMAGE_LATEST_TAG -t $IMAGE_RELEASE_TAG .
    - docker push $IMAGE_RELEASE_TAG
    - docker rmi $IMAGE_RELEASE_TAG
  <<: *release_tag_selector

docker:branch:
  stage: docker
  <<: *shared_docker_config
  script:
    - echo $CI_COMMIT_REF_SLUG
    - echo $IMAGE_BRANCH_TAG
    - docker pull $IMAGE_LATEST_TAG
    - docker build --cache-from $IMAGE_LATEST_TAG -t $IMAGE_BRANCH_TAG .
    - docker rmi $IMAGE_BRANCH_TAG
  only:
    - merge_requests

docker-push:branch:
  stage: docker-push
  <<: *shared_docker_config
  script:
    - docker pull $IMAGE_LATEST_TAG
    - docker build --cache-from $IMAGE_LATEST_TAG -t $IMAGE_BRANCH_TAG .
    - docker push $IMAGE_BRANCH_TAG
    - docker rmi $IMAGE_BRANCH_TAG
  only:
    - merge_requests
  when: manual
